services:
  configserver:
    image: rishabhmaloo/config-server:1.0.0
    container_name: "configserver"
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - ukg-payroll

  eurekaserver:
    image: rishabhmaloo/eureka-server:1.0.0
    container_name: eureka-server
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ukg-payroll

  salary:
    image: rishabhmaloo/salary:1.0.1
    container_name: "salary"
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ukg-payroll

  leave:
    image: vishalsaini410/leave:1.0.1
    container_name: "leave"
    ports:
      - 9000:8080
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ukg-payroll

  employee:
    image: rishabhmaloo/employee:1.0.0
    container_name: employee
    ports:
      - 9001:8080
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ukg-payroll

  payroll:
    image: prateekbhat165/payroll:1.0.2
    container_name: "payroll"
    ports:
      - 9002:8080
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      start_period: 45s
      interval: 5m
      timeout: 2m
      retries: 5
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    networks:
      - ukg-payroll

networks:
  ukg-payroll:
    driver: "bridge"